apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: otel-system
  labels:
    app: dotnet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: spring-java-2-dotnet-app:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: OTEL_SERVICE_NAME
          value: "dotnet-app"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=dotnet-app,service.version=1.0.0"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: PORT
          value: "5000"
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:5000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app
  namespace: otel-system
  labels:
    app: dotnet-app
spec:
  selector:
    app: dotnet-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
