apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: otel-system
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: spring-java-2-java-app:clean
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 8080
          name: http
        env:
        # Spring Boot native OTLP support (no agent, no full SDK)
        - name: MANAGEMENT_METRICS_EXPORT_OTLP_ENABLED
          value: "true"
        - name: MANAGEMENT_OTLP_METRICS_EXPORT_URL
          value: "http://otel-collector:4318/v1/metrics"
        - name: MANAGEMENT_METRICS_EXPORT_OTLP_RESOURCE_ATTRIBUTES
          value: "service.name=java-spring-app,service.version=1.0.0"
        - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
          value: "1.0"
        - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
          value: "http://otel-collector:4318/v1/traces"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info,metrics,prometheus"
        - name: MANAGEMENT_ENDPOINT_METRICS_ENABLED
          value: "false"
        - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
          value: "false"
        - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
          value: "false"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: otel-system
  labels:
    app: java-app
spec:
  selector:
    app: java-app
  ports:
  - name: http
    port: 9000
    targetPort: 8080
  type: ClusterIP
