name: Security Scan (.NET Alpine)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: read
  security-events: write

jobs:
  dotnet-alpine-trivy:
    name: .NET Alpine Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build .NET (Alpine) image
        run: |
          docker build \
            -f dotnet-spring-equivalent/Dockerfile.alpine \
            -t dotnet-app:alpine \
            ./dotnet-spring-equivalent
      
      - name: Run Trivy vulnerability scanner
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD:/workspace \
            aquasec/trivy:latest \
            --exit-code 0 \
            --format sarif \
            --output /workspace/trivy-results-dotnet-alpine.sarif \
            dotnet-app:alpine

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results-dotnet-alpine.sarif

      - name: Upload scan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-alpine-trivy
          path: |
            trivy-results-dotnet-alpine.sarif
